services:
  backend:
    build: ./backend
    depends_on:
      - mongo
      - redis
    environment:
      SECRETS_MASTER_KEYS: ${SECRETS_MASTER_KEYS}
    ports:
      - "31126:31126"
    networks:
      - mongo
      - redis
      - backend

  frontend:
    build:
      context: ./frontend
      dockerfile: dist/Dockerfile
    container_name: sveltekit-frontend
    networks:
      - frontend

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    networks:
      - mongo
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7.4-alpine
    ports:
      - "6379:6379"
    networks:
      - redis

  alb:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - frontend
      - backend

networks:
  mongo: {}
  redis: {}
  frontend: {}
  backend: {}

volumes:
  mongo_data: {}
